// State data ported from dmv.html STATES array.

export type StateTag = "eb3" | "notax" | "viet" | "resort";
export type BadgeVariant = "eb3" | "resort" | "food";

export interface StateEntry {
  flag: string;
  name: string;
  abbr: string;
  href: string;
  q: number;
  pass: string;
  fee: string;
  tags: StateTag[];
  badge: BadgeVariant;
  badgeLabel: string;
  employers: string;
  note: string;
}

export const STATES: StateEntry[] = [
  {
    flag: "🍑",
    name: "Georgia",
    abbr: "GA",
    href: "/bmv-ga",
    q: 40,
    pass: "75%",
    fee: "$10",
    tags: ["eb3", "viet"],
    badge: "eb3",
    badgeLabel: "Nhiều hãng nhất",
    employers: "Wayne Farms · Koch Foods · Claxton Poultry · Harrison Poultry · Farbest",
    note: "Nhiều hãng EB3 nhất, cộng đồng Việt Atlanta ~30K",
  },
  {
    flag: "⭐",
    name: "Texas",
    abbr: "TX",
    href: "/bmv-tx",
    q: 30,
    pass: "70%",
    fee: "$16",
    tags: ["notax", "viet"],
    badge: "eb3",
    badgeLabel: "Không thuế TN",
    employers: "SnD Manufacturing · Sentech Services · Labor Guys",
    note: "Không thuế TN · Cộng đồng Việt Houston 100K+",
  },
  {
    flag: "🌴",
    name: "Florida",
    abbr: "FL",
    href: "/bmv-fl",
    q: 50,
    pass: "80%",
    fee: "$48",
    tags: ["notax", "viet"],
    badge: "resort",
    badgeLabel: "Không thuế TN",
    employers: "FAENA · Rassy Logistics · Ocean Air · Nature's Way",
    note: "Không thuế TN · Resort · Logistics · Nông sản",
  },
  {
    flag: "🚗",
    name: "Indiana",
    abbr: "IN",
    href: "/bmv",
    q: 50,
    pass: "80%",
    fee: "$18",
    tags: ["eb3"],
    badge: "eb3",
    badgeLabel: "Labor Guys",
    employers: "Labor Guys LLC · Farbest Foods · Subway",
    note: "Labor Guys có nhiều slot · Chi phí vừa · 4 mùa",
  },
  {
    flag: "🧀",
    name: "Wisconsin",
    abbr: "WI",
    href: "/bmv-wi",
    q: 50,
    pass: "80%",
    fee: "$35",
    tags: ["eb3", "resort"],
    badge: "resort",
    badgeLabel: "Resort WI Dells",
    employers: "Wilderness Hotel · Chula Vista · Stoughton Trailer · Abbyland",
    note: "Resort Wisconsin Dells · Nhà máy · OWI (không DUI)",
  },
  {
    flag: "🌲",
    name: "N. Carolina",
    abbr: "NC",
    href: "/bmv-nc",
    q: 40,
    pass: "75%",
    fee: "$18",
    tags: ["eb3"],
    badge: "eb3",
    badgeLabel: "Gia cầm",
    employers: "Wayne Farms (Dobson) · Case Farms · Defender Service",
    note: "Nhiều hãng gia cầm · 4 mùa đẹp · Kinh tế phát triển",
  },
  {
    flag: "🌊",
    name: "S. Carolina",
    abbr: "SC",
    href: "/bmv-sc",
    q: 30,
    pass: "80%",
    fee: "$50",
    tags: ["eb3"],
    badge: "eb3",
    badgeLabel: "Stefan's Law",
    employers: "Zaxby's · SEJ Services · Battle Lumber · Nhà hàng GVL",
    note: "Stefan's Law (Move Over) · BMW/Michelin có nhà máy",
  },
  {
    flag: "🌶️",
    name: "Alabama",
    abbr: "AL",
    href: "/bmv-al",
    q: 40,
    pass: "80%",
    fee: "$36",
    tags: ["eb3"],
    badge: "eb3",
    badgeLabel: "Helmet bắt buộc",
    employers: "Koch Foods (Gadsden) · Hãng Cá Eutaw",
    note: "Chi phí thấp nhất · Helmet xe máy bắt buộc tất cả",
  },
  {
    flag: "🎡",
    name: "Ohio",
    abbr: "OH",
    href: "/bmv-oh",
    q: 40,
    pass: "75%",
    fee: "$23",
    tags: ["eb3"],
    badge: "eb3",
    badgeLabel: "Case Farms",
    employers: "Case Farms (OH) · Hãng sản xuất vùng Columbus",
    note: "Chi phí vừa · Columbus có cộng đồng Việt phát triển",
  },
  {
    flag: "🌨️",
    name: "Minnesota",
    abbr: "MN",
    href: "/bmv-mn",
    q: 40,
    pass: "80%",
    fee: "$32",
    tags: ["viet"],
    badge: "resort",
    badgeLabel: "TPI Hospitality",
    employers: "TPI Hospitality · Khách sạn Minneapolis",
    note: "Cộng đồng Việt ~20K · Mùa đông rất lạnh · Thuế cao",
  },
  {
    flag: "🔔",
    name: "Pennsylvania",
    abbr: "PA",
    href: "/bmv-pa",
    q: 18,
    pass: "83%",
    fee: "$35",
    tags: ["eb3"],
    badge: "eb3",
    badgeLabel: "Labor Guys",
    employers: "Labor Guys (Allentown) · Nhà máy vùng Allentown",
    note: "Gần NYC/Philly · Thuế 3.07% thấp · 4 mùa",
  },
  {
    flag: "🎰",
    name: "Nevada (Reno)",
    abbr: "NV",
    href: "/bmv-nv",
    q: 50,
    pass: "80%",
    fee: "$25",
    tags: ["notax"],
    badge: "eb3",
    badgeLabel: "Không thuế TN",
    employers: "Labor Guys (Reno) · Logistics Reno",
    note: "KHÔNG thuế TN · Helmet bắt buộc tất cả · Reno khác Las Vegas",
  },
  {
    flag: "🏔️",
    name: "Montana",
    abbr: "MT",
    href: "/bmv-mt",
    q: 33,
    pass: "82%",
    fee: "$25",
    tags: ["eb3"],
    badge: "eb3",
    badgeLabel: "Karst Stage",
    employers: "Karst Stage · Vehicle cleaning tours",
    note: "Thiên nhiên đẹp nhất Mỹ · Interstate 80 mph · Mùa đông khắc nghiệt",
  },
  {
    flag: "🎷",
    name: "Louisiana",
    abbr: "LA",
    href: "/bmv-la",
    q: 40,
    pass: "80%",
    fee: "$18",
    tags: ["viet", "eb3"],
    badge: "eb3",
    badgeLabel: "Catfish",
    employers: "Hãng Cá Catfish LA · Chế biến thủy sản",
    note: "Cộng đồng Việt New Orleans lâu đời ~25K · Nguy cơ bão",
  },
  {
    flag: "🐟",
    name: "Mississippi",
    abbr: "MS",
    href: "/bmv-ms",
    q: 30,
    pass: "80%",
    fee: "$20",
    tags: ["eb3"],
    badge: "eb3",
    badgeLabel: "Catfish · Thủy sản",
    employers: "Hãng Cá Catfish MS · Chế biến tôm",
    note: "Chi phí thấp nhất Mỹ · Ít cộng đồng Việt",
  },
  {
    flag: "🐔",
    name: "Arkansas",
    abbr: "AR",
    href: "/bmv-ar",
    q: 25,
    pass: "80%",
    fee: "$22",
    tags: ["eb3"],
    badge: "eb3",
    badgeLabel: "Peco Foods",
    employers: "Peco Foods · Koch Foods AR · Tyson Foods",
    note: "Chi phí rất thấp · Thiên nhiên đẹp",
  },
  {
    flag: "🦬",
    name: "S. Dakota",
    abbr: "SD",
    href: "/bmv-sd",
    q: 25,
    pass: "80%",
    fee: "$20",
    tags: ["notax"],
    badge: "eb3",
    badgeLabel: "Không thuế TN",
    employers: "Dakota Provision · Baldwin Filters",
    note: "Không thuế TN · Mùa đông khắc nghiệt",
  },
  {
    flag: "🌵",
    name: "Arizona",
    abbr: "AZ",
    href: "/bmv-az",
    q: 30,
    pass: "80%",
    fee: "$25",
    tags: ["notax"],
    badge: "eb3",
    badgeLabel: "Không thuế TN",
    employers: "Labor Guys Arizona · Logistics Phoenix",
    note: "Không thuế TN · Nóng mùa hè · Phoenix",
  },
];
