import { getCloudflareContext } from "@opennextjs/cloudflare";
import staticFallback from "@/data/visa-bulletin.json";
import type { VisaBulletinData } from "./types";

// KV key written by .github/workflows/fetch-visa-bulletin.yml's
// `wrangler kv key put` step (see scripts/fetch-visa-bulletin.py for the
// fetch+parse logic that produces this JSON).
const KV_KEY = "visa-bulletin-data";

// Augment CloudflareEnv (declared by @opennextjs/cloudflare) with the KV
// binding shape. Inline object type avoids referencing `KVNamespace` by name —
// worker-configuration.d.ts (gitignored, generated by `wrangler types`) is not
// present in CI so any named reference to KVNamespace would fail type checking.
declare global {
  interface CloudflareEnv {
    VISA_BULLETIN: {
      get(key: string, options?: { type?: string }): Promise<string | null>;
      put(key: string, value: string | ArrayBuffer): Promise<void>;
      delete(key: string): Promise<void>;
    };
  }
}

function isValidVisaBulletinData(value: unknown): value is VisaBulletinData {
  if (typeof value !== "object" || value === null) return false;
  const candidate = value as Record<string, unknown>;
  return (
    typeof candidate.updated === "string" &&
    typeof candidate.fy === "number" &&
    typeof candidate.fy_start_month === "string" &&
    Array.isArray(candidate.months) &&
    typeof candidate.carry_over === "object" &&
    candidate.carry_over !== null
  );
}

/**
 * Shared KV-read-with-fallback used by both /api/visa-bulletin (client
 * dashboard fetch) and server components that need the same data at render
 * time (e.g. the homepage's VbSnapCard) — one read implementation, never a
 * blank/stale render if KV is unavailable.
 */
export async function getVisaBulletinData(): Promise<VisaBulletinData> {
  try {
    const { env } = await getCloudflareContext({ async: true });
    const raw = await env.VISA_BULLETIN.get(KV_KEY);

    if (raw) {
      const parsed: unknown = JSON.parse(raw);
      if (isValidVisaBulletinData(parsed)) {
        return parsed;
      }
      console.error("getVisaBulletinData: KV data failed shape validation, falling back to static JSON");
    }
  } catch (error) {
    console.error("getVisaBulletinData: KV read failed, falling back to static JSON", error);
  }

  return staticFallback as VisaBulletinData;
}
