import type { QuizQuestion } from "../components/bmv-quiz-engine";

export const PA_PASS_COUNT = 15;

export const PA_QUESTIONS: QuizQuestion[] = [
  {en:"PA knowledge test — how many questions and passing score?",vi:"Kỳ thi lý thuyết PA có bao nhiêu câu và điểm đậu?",opts:[{en:"25 questions, 80%",vi:"25 questions, 80%"},{en:"18 questions, 83% — 15 correct",vi:"18 questions, 83% — 15 correct"},{en:"50 questions, 80%",vi:"50 questions, 80%"},{en:"40 questions, 75%",vi:"40 questions, 75%"}],ans:1,exp:{en:"Pennsylvania requires 15 out of 18 correct (83%) to pass.",vi:"PA yêu cầu 15/18 câu đúng (83%) để đậu."}},
  {en:"Default speed in PA residential areas?",vi:"Tốc độ mặc định khu dân cư PA?",opts:[{en:"20 mph",vi:"20 mph"},{en:"25 mph",vi:"25 mph"},{en:"30 mph",vi:"30 mph"},{en:"35 mph",vi:"35 mph"}],ans:1,exp:{en:"Pennsylvania residential areas default to 25 mph.",vi:"Khu dân cư PA mặc định 25 mph."}},
  {en:"PA DUI limit for under 21?",vi:"Giới hạn DUI dưới 21t ở PA?",opts:[{en:"0.08%",vi:"0.08%"},{en:"0.04%",vi:"0.04%"},{en:"0.02%",vi:"0.02%"},{en:"Zero tolerance",vi:"Zero tolerance"}],ans:2,exp:{en:"PA uses a 0.02% BAC limit for drivers under 21.",vi:"PA: BAC >=0.02% cho người dưới 21t là DUI."}},
  {en:"PA motorcycle helmets required for:",vi:"Mũ xe máy PA bắt buộc cho:",opts:[{en:"All riders",vi:"All riders"},{en:"Under 21 and those with less than 2 years license",vi:"Under 21 and those with less than 2 years license"},{en:"Only on highways",vi:"Only on highways"},{en:"No one",vi:"No one"}],ans:1,exp:{en:"PA requires helmets for under 21 and those with license less than 2 years.",vi:"PA bắt buộc mũ cho dưới 21t và người có bằng xe máy dưới 2 năm."}},
  {en:"School zone speed in PA?",vi:"Tốc độ khu trường học PA?",opts:[{en:"10 mph",vi:"10 mph"},{en:"15 mph",vi:"15 mph"},{en:"20 mph",vi:"20 mph"},{en:"25 mph",vi:"25 mph"}],ans:1,exp:{en:"Pennsylvania school zones: 15 mph when flashing lights are active.",vi:"Khu trường học PA: 15 mph khi đèn nhấp nháy."}},
  {en:"Right on red in PA?",vi:"Rẽ phải khi đèn đỏ ở PA?",opts:[{en:"Never",vi:"Never"},{en:"Yes, after stop and yield unless prohibited",vi:"Yes, after stop and yield unless prohibited"},{en:"Only green arrow",vi:"Only green arrow"},{en:"Always",vi:"Always"}],ans:1,exp:{en:"Right on red after complete stop and yielding, unless a NO TURN ON RED sign.",vi:"Được rẽ phải sau khi dừng và nhường, trừ khi có biển NO TURN ON RED."}},
  {en:"PA minimum liability insurance?",vi:"Bảo hiểm tối thiểu PA là?",opts:[{en:"$25,000/$50,000/$25,000",vi:"$25,000/$50,000/$25,000"},{en:"$15,000/$30,000/$5,000",vi:"$15,000/$30,000/$5,000"},{en:"$30,000/$60,000/$25,000",vi:"$30,000/$60,000/$25,000"},{en:"No requirement",vi:"No requirement"}],ans:1,exp:{en:"PA minimum: $15,000 per person / $30,000 per accident / $5,000 property damage.",vi:"PA tối thiểu: $15K/người · $30K/tai nạn · $5K hư hại tài sản."}},
  {en:"School bus red lights flashing in PA:",vi:"Xe buýt trường học đèn đỏ nhấp nháy ở PA:",opts:[{en:"Slow to 20 mph",vi:"Slow to 20 mph"},{en:"Stop both directions unless median",vi:"Stop both directions unless median"},{en:"Proceed carefully",vi:"Proceed carefully"},{en:"Stop only if behind",vi:"Stop only if behind"}],ans:1,exp:{en:"Stop in both directions when school bus has red lights flashing.",vi:"Dừng cả 2 chiều khi xe buýt đèn đỏ nhấp nháy."}},
  {en:"What does a two-way left turn lane (TWLTL) mean?",vi:"Làn rẽ trái 2 chiều (TWLTL) có nghĩa gì?",opts:[{en:"U-turns only",vi:"U-turns only"},{en:"Center lane with yellow on both sides for left turns by both directions",vi:"Center lane with yellow on both sides for left turns by both directions"},{en:"Bus lane only",vi:"Bus lane only"},{en:"Signal turn lane only",vi:"Signal turn lane only"}],ans:1,exp:{en:"TWLTL has yellow lines on both sides and is used ONLY for left turns.",vi:"TWLTL có vạch vàng cả 2 bên, CHỈ dùng để rẽ trái."}},
  {en:"Signal before turning in PA?",vi:"Bật xi-nhan trước khi rẽ ở PA bao xa?",opts:[{en:"50 feet",vi:"50 feet"},{en:"100 feet",vi:"100 feet"},{en:"200 feet",vi:"200 feet"},{en:"At the turn",vi:"At the turn"}],ans:1,exp:{en:"PA requires signaling at least 100 feet before a turn or lane change.",vi:"PA yêu cầu xi-nhan ít nhất 100 feet trước khi rẽ hoặc đổi làn."}},
  {en:"When must headlights be on in PA?",vi:"Khi nào phải bật đèn pha ở PA?",opts:[{en:"Only at night",vi:"Only at night"},{en:"30 min after sunset to 30 min before sunrise, in rain/fog",vi:"30 min after sunset to 30 min before sunrise, in rain/fog"},{en:"Only heavy rain",vi:"Only heavy rain"},{en:"Highways only",vi:"Highways only"}],ans:1,exp:{en:"PA headlights: 30 min after sunset to 30 min before sunrise, and when visibility is reduced.",vi:"PA: đèn pha từ 30 phút sau hoàng hôn đến 30 phút trước bình minh, và khi tầm nhìn giảm."}},
  {en:"Recommended following distance in PA?",vi:"Khoảng cách theo sau PA?",opts:[{en:"1 second",vi:"1 second"},{en:"2 seconds",vi:"2 seconds"},{en:"3 seconds",vi:"3 seconds"},{en:"4 seconds",vi:"4 seconds"}],ans:2,exp:{en:"PA recommends minimum 3-second following distance.",vi:"PA khuyến nghị tối thiểu 3 giây."}},
  {en:"PA pentagon sign means:",vi:"Biển ngũ giác ở PA chỉ điều gì?",opts:[{en:"Railroad crossing",vi:"Railroad crossing"},{en:"School zone/crossing",vi:"School zone/crossing"},{en:"Construction",vi:"Construction"},{en:"Highway",vi:"Highway"}],ans:1,exp:{en:"Pentagon signs are ONLY for school zone and school crossing warnings.",vi:"Biển ngũ giác CHỈ dùng cho biển khu trường học và lối sang đường trường học."}},
  {en:"Emergency vehicle approaching in PA:",vi:"Xe cứu thương tiến lại ở PA:",opts:[{en:"Speed up",vi:"Speed up"},{en:"Pull right and stop",vi:"Pull right and stop"},{en:"Move to center",vi:"Move to center"},{en:"Keep going",vi:"Keep going"}],ans:1,exp:{en:"Pull to the right and stop until all emergency vehicles pass.",vi:"Kéo vào lề phải và dừng cho đến khi xe cứu thương qua."}},
  {en:"Seat belts in PA:",vi:"Dây an toàn ở PA:",opts:[{en:"Only front seats",vi:"Only front seats"},{en:"All occupants",vi:"All occupants"},{en:"Only under 18",vi:"Only under 18"},{en:"Only driver",vi:"Only driver"}],ans:1,exp:{en:"PA requires all vehicle occupants to wear seat belts.",vi:"PA bắt buộc tất cả người trong xe thắt dây an toàn."}},
  {en:"Highway guide signs in PA are what color?",vi:"Biển hướng dẫn trên cao tốc PA có màu gì?",opts:[{en:"Yellow",vi:"Yellow"},{en:"Orange",vi:"Orange"},{en:"Green with white letters",vi:"Green with white letters"},{en:"Blue",vi:"Blue"}],ans:2,exp:{en:"Guide signs on highways are green with white letters.",vi:"Biển hướng dẫn trên cao tốc màu xanh lá với chữ trắng."}},
  {en:"What does a flashing yellow light mean?",vi:"Đèn vàng nhấp nháy có nghĩa gì?",opts:[{en:"Stop",vi:"Stop"},{en:"Proceed with caution",vi:"Proceed with caution"},{en:"Same as STOP",vi:"Same as STOP"},{en:"Emergency ahead",vi:"Emergency ahead"}],ans:1,exp:{en:"Flashing yellow: slow down and proceed with caution.",vi:"Đèn vàng nhấp nháy: giảm tốc và đi qua thận trọng."}},
  {en:"PA Move Over Law:",vi:"Luật Move Over PA:",opts:[{en:"Stop for all vehicles",vi:"Stop for all vehicles"},{en:"Move over or slow when passing stopped emergency/service vehicles on shoulder",vi:"Move over or slow when passing stopped emergency/service vehicles on shoulder"},{en:"Flash lights",vi:"Flash lights"},{en:"Highways only",vi:"Highways only"}],ans:1,exp:{en:"Move over or reduce speed when passing stopped emergency, tow, or utility vehicles on shoulder.",vi:"Chuyển làn hoặc giảm tốc khi qua xe cứu thương/kéo/tiện ích dừng ven đường."}},
];
