import { getCloudflareContext } from "@opennextjs/cloudflare";
import staticFallback from "@/data/visa-bulletin.json";
import type { VisaBulletinData } from "../../visa-bulletin/types";

// KV key written by .github/workflows/fetch-visa-bulletin.yml's
// `wrangler kv key put` step (see scripts/fetch-visa-bulletin.py for the
// fetch+parse logic that produces this JSON).
const KV_KEY = "visa-bulletin-data";

// Edge-cache window: data updates at most ~daily (GH Actions cron), so a
// few minutes of edge caching avoids hammering KV reads on every page view
// without risking meaningfully stale data.
const CACHE_CONTROL = "public, max-age=300, s-maxage=300";

// Augment CloudflareEnv (declared by @opennextjs/cloudflare) with the KV
// binding used by this route. KVNamespace is also declared here inside
// `declare global` because this file has import statements, making any
// top-level interface declaration module-scoped rather than global — the
// reference inside `declare global` must resolve in global scope.
// worker-configuration.d.ts (gitignored, generated by `wrangler types`)
// provides a fuller version in local dev; this minimal shape is enough for CI.
declare global {
  interface KVNamespace {
    get(key: string, options?: { type?: string }): Promise<string | null>;
    put(key: string, value: string | ArrayBuffer): Promise<void>;
    delete(key: string): Promise<void>;
  }
  interface CloudflareEnv {
    VISA_BULLETIN: KVNamespace;
  }
}

function isValidVisaBulletinData(value: unknown): value is VisaBulletinData {
  if (typeof value !== "object" || value === null) return false;
  const candidate = value as Record<string, unknown>;
  return (
    typeof candidate.updated === "string" &&
    typeof candidate.fy === "number" &&
    typeof candidate.fy_start_month === "string" &&
    Array.isArray(candidate.months) &&
    typeof candidate.carry_over === "object" &&
    candidate.carry_over !== null
  );
}

export async function GET() {
  try {
    const { env } = await getCloudflareContext({ async: true });
    const raw = await env.VISA_BULLETIN.get(KV_KEY);

    if (raw) {
      const parsed: unknown = JSON.parse(raw);
      if (isValidVisaBulletinData(parsed)) {
        return Response.json(parsed, {
          headers: { "Cache-Control": CACHE_CONTROL },
        });
      }
      console.error("visa-bulletin API: KV data failed shape validation, falling back to static JSON");
    }
  } catch (error) {
    // Fail-safe: never a blank chart. Log and fall back to the bundled
    // static snapshot (e.g. KV unavailable in local dev, or read error).
    console.error("visa-bulletin API: KV read failed, falling back to static JSON", error);
  }

  return Response.json(staticFallback as VisaBulletinData, {
    headers: { "Cache-Control": CACHE_CONTROL },
  });
}
