import { getCloudflareContext } from "@opennextjs/cloudflare";
import staticFallback from "@/data/visa-bulletin.json";
import type { VisaBulletinData } from "../../visa-bulletin/types";

// KV key written by .github/workflows/fetch-visa-bulletin.yml's
// `wrangler kv key put` step (see scripts/fetch-visa-bulletin.py for the
// fetch+parse logic that produces this JSON).
const KV_KEY = "visa-bulletin-data";

// Edge-cache window: data updates at most ~daily (GH Actions cron), so a
// few minutes of edge caching avoids hammering KV reads on every page view
// without risking meaningfully stale data.
const CACHE_CONTROL = "public, max-age=300, s-maxage=300";

// `getCloudflareContext().env` is typed as the `CloudflareEnv` global
// interface (declared by @opennextjs/cloudflare), which is a *different*
// interface than the `Env` one generated by `wrangler types` into
// worker-configuration.d.ts (a known opennextjs-cloudflare naming gap —
// see opennext.js.org/cloudflare/bindings). Augmenting CloudflareEnv here,
// scoped to this file only, avoids touching the generated .d.ts or any
// wrangler config.
declare global {
  interface CloudflareEnv {
    VISA_BULLETIN: KVNamespace;
  }
}

function isValidVisaBulletinData(value: unknown): value is VisaBulletinData {
  if (typeof value !== "object" || value === null) return false;
  const candidate = value as Record<string, unknown>;
  return (
    typeof candidate.updated === "string" &&
    typeof candidate.fy === "number" &&
    typeof candidate.fy_start_month === "string" &&
    Array.isArray(candidate.months) &&
    typeof candidate.carry_over === "object" &&
    candidate.carry_over !== null
  );
}

export async function GET() {
  try {
    const { env } = await getCloudflareContext({ async: true });
    const raw = await env.VISA_BULLETIN.get(KV_KEY);

    if (raw) {
      const parsed: unknown = JSON.parse(raw);
      if (isValidVisaBulletinData(parsed)) {
        return Response.json(parsed, {
          headers: { "Cache-Control": CACHE_CONTROL },
        });
      }
      console.error("visa-bulletin API: KV data failed shape validation, falling back to static JSON");
    }
  } catch (error) {
    // Fail-safe: never a blank chart. Log and fall back to the bundled
    // static snapshot (e.g. KV unavailable in local dev, or read error).
    console.error("visa-bulletin API: KV read failed, falling back to static JSON", error);
  }

  return Response.json(staticFallback as VisaBulletinData, {
    headers: { "Cache-Control": CACHE_CONTROL },
  });
}
