import type { QuizQuestion } from "../components/bmv-quiz-engine";

export const OH_PASS_COUNT = 30;

export const OH_QUESTIONS: QuizQuestion[] = [
  {en:"What is Ohio's term for impaired driving?",vi:"Ohio dùng thuật ngữ nào cho lái xe say rượu?",opts:[{en:"DUI",vi:"DUI"},{en:"DWI",vi:"DWI"},{en:"OVI — Operating Vehicle Impaired",vi:"OVI — Operating Vehicle Impaired"},{en:"BWI",vi:"BWI"}],ans:2,exp:{en:"Ohio uses OVI (Operating Vehicle Impaired). BAC 0.08%+ for adults is illegal.",vi:"Ohio dùng OVI không phải DUI. BAC >= 0.08% với người lớn là phạm pháp."}},
  {en:"What is the default speed limit in Ohio residential areas?",vi:"Tốc độ mặc định khu dân cư Ohio?",opts:[{en:"20 mph",vi:"20 mph"},{en:"25 mph",vi:"25 mph"},{en:"30 mph",vi:"30 mph"},{en:"35 mph",vi:"35 mph"}],ans:1,exp:{en:"Ohio residential areas default to 25 mph.",vi:"Khu dân cư Ohio mặc định 25 mph."}},
  {en:"What is the speed limit on Ohio interstate highways?",vi:"Tốc độ trên interstate Ohio?",opts:[{en:"55 mph",vi:"55 mph"},{en:"60 mph",vi:"60 mph"},{en:"65 mph",vi:"65 mph"},{en:"70 mph",vi:"70 mph"}],ans:3,exp:{en:"Ohio interstate highways have a default speed limit of 70 mph.",vi:"Interstate Ohio có giới hạn mặc định 70 mph."}},
  {en:"Are motorcycle helmets required for adults in Ohio?",vi:"Ohio có bắt buộc mũ bảo hiểm cho người lớn không?",opts:[{en:"Yes for all",vi:"Yes for all"},{en:"No, not required for 18 and older",vi:"No, not required for 18 and older"},{en:"Only on highways",vi:"Only on highways"},{en:"Only passengers",vi:"Only passengers"}],ans:1,exp:{en:"Ohio does NOT require helmets for riders 18 and older.",vi:"Ohio KHÔNG bắt buộc mũ bảo hiểm cho người từ 18t trở lên."}},
  {en:"What is the school zone speed limit in Ohio?",vi:"Tốc độ khu trường học Ohio?",opts:[{en:"15 mph",vi:"15 mph"},{en:"20 mph",vi:"20 mph"},{en:"25 mph",vi:"25 mph"},{en:"30 mph",vi:"30 mph"}],ans:1,exp:{en:"Ohio school zones: 20 mph when lights flash or children are present.",vi:"Khu trường học Ohio: 20 mph khi đèn nhấp nháy hoặc có trẻ em."}},
  {en:"Ohio Move Over Law requires:",vi:"Luật Move Over Ohio yêu cầu:",opts:[{en:"Stop completely",vi:"Stop completely"},{en:"Move over or slow significantly when passing stopped emergency vehicles",vi:"Move over or slow significantly when passing stopped emergency vehicles"},{en:"Flash headlights",vi:"Flash headlights"},{en:"Only for police",vi:"Only for police"}],ans:1,exp:{en:"Move over one lane OR reduce speed significantly when passing stopped emergency or service vehicles.",vi:"Chuyển làn HOẶC giảm tốc đáng kể khi qua xe cứu thương/kéo dừng ven đường."}},
  {en:"In Ohio, seat belts are required for:",vi:"Dây an toàn Ohio bắt buộc cho:",opts:[{en:"Only driver",vi:"Only driver"},{en:"Driver and front passengers",vi:"Driver and front passengers"},{en:"All occupants",vi:"All occupants"},{en:"Only under 18",vi:"Only under 18"}],ans:2,exp:{en:"Ohio requires ALL vehicle occupants to wear seat belts.",vi:"Ohio bắt buộc tất cả người trong xe thắt dây an toàn."}},
  {en:"What does a flashing red light mean in Ohio?",vi:"Đèn đỏ nhấp nháy ở Ohio có nghĩa gì?",opts:[{en:"Yield",vi:"Yield"},{en:"Treat as a STOP sign",vi:"Treat as a STOP sign"},{en:"Proceed with caution",vi:"Proceed with caution"},{en:"Emergency vehicle",vi:"Emergency vehicle"}],ans:1,exp:{en:"A flashing red means treat it like a STOP sign: stop, yield, proceed when safe.",vi:"Đèn đỏ nhấp nháy = biển STOP: dừng hoàn toàn, nhường, đi khi an toàn."}},
  {en:"Can you turn right on red in Ohio?",vi:"Được rẽ phải khi đèn đỏ ở Ohio không?",opts:[{en:"Never",vi:"Never"},{en:"Yes, after stopping and yielding, unless sign prohibits",vi:"Yes, after stopping and yielding, unless sign prohibits"},{en:"Only green arrow",vi:"Only green arrow"},{en:"Any time",vi:"Any time"}],ans:1,exp:{en:"Right on red is permitted after a complete stop and yielding unless a sign prohibits it.",vi:"Được rẽ phải sau khi dừng và nhường, trừ khi có biển cấm."}},
  {en:"Texting while driving in Ohio is:",vi:"Nhắn tin khi lái xe ở Ohio là:",opts:[{en:"Legal for adults",vi:"Legal for adults"},{en:"Illegal for all drivers",vi:"Illegal for all drivers"},{en:"Only illegal under 18",vi:"Only illegal under 18"},{en:"Legal at red lights",vi:"Legal at red lights"}],ans:1,exp:{en:"Texting while driving is illegal for ALL drivers in Ohio.",vi:"Nhắn tin khi lái là bất hợp pháp cho TẤT CẢ tài xế ở Ohio."}},
  {en:"At a 4-way stop in Ohio, if two cars arrive simultaneously:",vi:"Ngã tư STOP Ohio, 2 xe đến cùng lúc:",opts:[{en:"Larger vehicle first",vi:"Larger vehicle first"},{en:"Yield to vehicle on the right",vi:"Yield to vehicle on the right"},{en:"Going straight first",vi:"Going straight first"},{en:"Honk to claim",vi:"Honk to claim"}],ans:1,exp:{en:"When two vehicles arrive simultaneously, yield to the vehicle on your right.",vi:"2 xe đến cùng lúc: nhường xe ở bên phải bạn."}},
  {en:"Ohio minimum liability insurance:",vi:"Bảo hiểm tối thiểu Ohio là:",opts:[{en:"$25,000/$50,000/$25,000",vi:"$25,000/$50,000/$25,000"},{en:"$15,000/$30,000/$5,000",vi:"$15,000/$30,000/$5,000"},{en:"$30,000/$60,000/$25,000",vi:"$30,000/$60,000/$25,000"},{en:"No requirement",vi:"No requirement"}],ans:0,exp:{en:"Ohio minimum: $25,000 per person / $50,000 per accident / $25,000 property damage.",vi:"Ohio tối thiểu: $25K/người · $50K/tai nạn · $25K hư hại tài sản."}},
  {en:"When must headlights be on in Ohio?",vi:"Khi nào phải bật đèn pha ở Ohio?",opts:[{en:"Only at night",vi:"Only at night"},{en:"30 min after sunset to 30 min before sunrise, in rain/fog",vi:"30 min after sunset to 30 min before sunrise, in rain/fog"},{en:"Only in rain",vi:"Only in rain"},{en:"On highways only",vi:"On highways only"}],ans:1,exp:{en:"Headlights from 30 min after sunset to 30 min before sunrise, and in rain/fog.",vi:"Đèn pha từ 30 phút sau hoàng hôn đến 30 phút trước bình minh, và khi mưa/sương mù."}},
  {en:"When approaching school bus with red lights flashing:",vi:"Khi tiếp cận xe buýt trường học đèn đỏ nhấp nháy:",opts:[{en:"Slow to 15 mph",vi:"Slow to 15 mph"},{en:"Stop both directions unless median separates",vi:"Stop both directions unless median separates"},{en:"Honk and pass",vi:"Honk and pass"},{en:"Only stop if behind",vi:"Only stop if behind"}],ans:1,exp:{en:"Stop in both directions when a school bus has red lights flashing.",vi:"Dừng cả 2 chiều khi xe buýt đèn đỏ nhấp nháy."}},
  {en:"What does a solid yellow center line on your side mean?",vi:"Vạch vàng liền ở phía bạn có nghĩa gì?",opts:[{en:"Passing is allowed",vi:"Passing is allowed"},{en:"No passing from your side",vi:"No passing from your side"},{en:"Construction zone",vi:"Construction zone"},{en:"Speed zone",vi:"Speed zone"}],ans:1,exp:{en:"A solid yellow on YOUR side means you may NOT pass.",vi:"Vạch vàng liền ở phía BẠN = không được vượt."}},
  {en:"Green traffic light means:",vi:"Đèn xanh có nghĩa gì?",opts:[{en:"Go without yielding",vi:"Go without yielding"},{en:"Go but yield to pedestrians and vehicles in intersection",vi:"Go but yield to pedestrians and vehicles in intersection"},{en:"Speed up",vi:"Speed up"},{en:"Stop 3 seconds first",vi:"Stop 3 seconds first"}],ans:1,exp:{en:"Green means go but yield to pedestrians in crosswalks and vehicles already in intersection.",vi:"Xanh = đi nhưng nhường người đi bộ và xe đã trong giao lộ."}},
  {en:"How far before a turn must you signal in Ohio?",vi:"Phải bật xi-nhan trước khi rẽ bao xa ở Ohio?",opts:[{en:"50 feet",vi:"50 feet"},{en:"100 feet",vi:"100 feet"},{en:"200 feet",vi:"200 feet"},{en:"At the turn",vi:"At the turn"}],ans:1,exp:{en:"Ohio requires signaling at least 100 feet before turning or changing lanes.",vi:"Ohio yêu cầu bật xi-nhan ít nhất 100 feet trước khi rẽ hoặc đổi làn."}},
  {en:"Recommended following distance in Ohio?",vi:"Khoảng cách theo sau khuyến nghị ở Ohio?",opts:[{en:"1 second",vi:"1 second"},{en:"2 seconds",vi:"2 seconds"},{en:"3 seconds",vi:"3 seconds"},{en:"5 seconds",vi:"5 seconds"}],ans:2,exp:{en:"Ohio recommends a minimum 3-second following distance.",vi:"Ohio khuyến nghị tối thiểu 3 giây."}},
  {en:"Emergency vehicle approaching — you must:",vi:"Xe cứu thương tiến lại — bạn phải:",opts:[{en:"Speed up",vi:"Speed up"},{en:"Pull to the right and stop",vi:"Pull to the right and stop"},{en:"Move to center",vi:"Move to center"},{en:"Keep going",vi:"Keep going"}],ans:1,exp:{en:"Pull to the right side and stop until all emergency vehicles pass.",vi:"Kéo vào lề phải và dừng cho đến khi tất cả xe cứu thương qua."}},
  {en:"What shape is a warning sign?",vi:"Biển cảnh báo có hình dạng gì?",opts:[{en:"Octagon",vi:"Octagon"},{en:"Rectangle",vi:"Rectangle"},{en:"Diamond (rhombus)",vi:"Diamond (rhombus)"},{en:"Pentagon",vi:"Pentagon"}],ans:2,exp:{en:"Warning signs are yellow diamond-shaped.",vi:"Biển cảnh báo hình thoi vàng."}},
];
