/**
 * Interview Q&A bank ported from interview.html's inline `QS` array
 * (legacy lines 226-285). 50 questions across 5 categories, each with
 * an English sample answer, Vietnamese translation, and optional
 * warning/tip callouts.
 */
export type InterviewCategory = "1" | "2" | "3" | "4" | "5";

export interface InterviewQa {
  cat: InterviewCategory;
  q: string;
  vi: string;
  ans: string;
  viAns: string;
  warn?: string;
  tip?: string;
}

export const CATEGORY_LABELS: Record<InterviewCategory, string> = {
  "1": "🏢 Công Ty & EB-3",
  "2": "💼 Công Việc",
  "3": "👨‍👩‍👧 Cá Nhân",
  "4": "🇺🇸 Kế Hoạch",
  "5": "📋 Pháp Lý",
};

export const CATEGORY_BADGE_CLASSES: Record<InterviewCategory, string> = {
  "1": "bg-primary/20 text-primary",
  "2": "bg-accent/20 text-accent",
  "3": "bg-secondary/30 text-secondary",
  "4": "bg-orange-900/40 text-orange-300",
  "5": "bg-yellow-900/30 text-yellow-200",
};

export const CATEGORY_FILTERS: Array<{ key: InterviewCategory | "all"; label: string }> = [
  { key: "all", label: "Tất cả (50)" },
  { key: "1", label: "🏢 Về Công Ty & EB-3" },
  { key: "2", label: "💼 Công Việc" },
  { key: "3", label: "👨‍👩‍👧 Cá Nhân & Gia Đình" },
  { key: "4", label: "🇺🇸 Kế Hoạch Ở Mỹ" },
  { key: "5", label: "📋 Hồ Sơ & Pháp Lý" },
];

export const INTERVIEW_QUESTIONS: InterviewQa[] = [
  // CAT 1: Về Công Ty & EB-3 (10 câu)
  { cat: "1", q: "What is EB-3? Why are you applying for this visa?", vi: "EB-3 là gì? Tại sao bạn xin visa này?", ans: "EB-3 is an employment-based immigration visa. I am applying because a US company has offered me a full-time job that requires no specialized degree. They filed a Labor Certification showing no qualified American workers were available.", viAns: "EB-3 là visa định cư dựa trên việc làm. Tôi xin visa này vì một công ty Mỹ đã mời tôi làm việc toàn thời gian, không yêu cầu bằng cấp chuyên môn. Họ đã nộp LC chứng minh không tuyển được lao động Mỹ.", warn: "Nếu không trả lời được câu này — đây là dấu hiệu nguy hiểm. Nhân viên LSQ sẽ nghi ngờ bạn không hiểu hồ sơ của mình." },
  { cat: "1", q: "What is the name of the company sponsoring you?", vi: "Tên đầy đủ của công ty bảo trợ bạn là gì?", ans: "[Tên đầy đủ công ty — phải thuộc lòng, ví dụ: Koch Foods LLC / Wayne-Sanderson Farms LLC / Labor Guys LLC]", viAns: "[Phải biết tên đầy đủ, đúng chính xác như trên hợp đồng]", warn: "Không biết tên công ty = red flag nghiêm trọng. Tập thuộc tên đầy đủ bằng tiếng Anh.", tip: "Hỏi agency cung cấp tên chính xác như trên I-140. Đừng dùng tên rút gọn trừ khi đó là tên chính thức." },
  { cat: "1", q: "Where is the company located?", vi: "Công ty đặt ở đâu? Địa chỉ là gì?", ans: "The company is located at [địa chỉ đầy đủ: số nhà, đường, thành phố, tiểu bang, ZIP code].", viAns: "Công ty ở tại [địa chỉ đầy đủ]. Bạn phải biết ít nhất thành phố và tiểu bang.", warn: "Không biết địa chỉ công ty = không khả tín. Phải biết ít nhất thành phố và tiểu bang." },
  { cat: "1", q: "How did you find out about this job opportunity?", vi: "Bạn biết đến cơ hội việc làm này như thế nào?", ans: "I found out through [tên agency]. They introduced me to the employer who was looking for workers.", viAns: "Tôi biết đến qua [tên agency]. Họ giới thiệu tôi với nhà tuyển dụng đang cần lao động.", tip: "Trả lời thật. Không cần giấu việc qua agency — đây là hoàn toàn hợp pháp và phổ biến." },
  { cat: "1", q: "Did you pay any fees to get this job?", vi: "Bạn có trả phí nào để được việc làm này không?", ans: "I paid agency fees for immigration documentation assistance. The employer did not charge me for the job itself.", viAns: "Tôi trả phí dịch vụ cho agency hỗ trợ giấy tờ di trú. Nhà tuyển dụng không thu phí cho việc làm.", warn: "Câu này nhạy cảm. Lãnh sự quán muốn đảm bảo đây không phải lừa đảo. Nếu có phí, giải thích rõ đó là phí dịch vụ di trú, không phải \"mua job\".", tip: "Đây là câu kiểm tra \"trafficking\". Trả lời thẳng thắn, trung thực." },
  { cat: "1", q: "What is your wage/salary for this position?", vi: "Mức lương của bạn cho vị trí này là bao nhiêu?", ans: "My wage is [mức lương theo giờ, ví dụ: $15.50 per hour], which is the prevailing wage determined by the Department of Labor for this position.", viAns: "Mức lương của tôi là [$/giờ], là mức lương theo quy định DOL cho vị trí này.", warn: "Phải biết lương chính xác như trên hợp đồng. Sai lương = mâu thuẫn hồ sơ." },
  { cat: "1", q: "Is this a full-time, permanent position?", vi: "Đây có phải vị trí toàn thời gian, lâu dài không?", ans: "Yes, this is a full-time, permanent position working at least 35-40 hours per week.", viAns: "Vâng, đây là vị trí toàn thời gian, lâu dài, làm ít nhất 35-40 giờ mỗi tuần.", tip: "EB-3 yêu cầu full-time permanent job. Câu trả lời luôn phải là YES." },
  { cat: "1", q: "How long has the company been in operation?", vi: "Công ty đã hoạt động bao lâu?", ans: "I believe the company has been in operation for [số năm] years. It is an established business in [ngành nghề].", viAns: "Công ty đã hoạt động khoảng [số năm] năm. Đây là doanh nghiệp lâu năm trong ngành [nghề].", tip: "Hỏi agency về thông tin công ty. Biết sơ qua là đủ." },
  { cat: "1", q: "Will you definitely work for this company when you arrive in the US?", vi: "Bạn có chắc chắn sẽ làm việc cho công ty này khi sang Mỹ không?", ans: "Yes, absolutely. I have a signed employment contract and I am committed to fulfilling my work obligation to the company.", viAns: "Vâng, chắc chắn. Tôi có hợp đồng lao động đã ký và cam kết thực hiện đúng nghĩa vụ làm việc với công ty.", warn: "Câu này kiểm tra mục đích thật của bạn. Phải thể hiện cam kết mạnh mẽ với việc làm." },
  { cat: "1", q: "What are the working hours at this company?", vi: "Giờ làm việc tại công ty như thế nào?", ans: "The working hours are [ví dụ: Monday to Friday, 6am to 2:30pm]. There may also be overtime available.", viAns: "Giờ làm việc là [ví dụ: thứ 2 đến thứ 6, 6 giờ sáng đến 2:30 chiều]. Có thể có overtime.", tip: "Hỏi agency về lịch làm việc thực tế. Biết sơ là đủ." },

  // CAT 2: Công Việc (10 câu)
  { cat: "2", q: "What is your job title?", vi: "Chức danh công việc của bạn là gì?", ans: "My job title is [ví dụ: Production Worker / Poultry Processing Worker / Warehouse Associate].", viAns: "Chức danh của tôi là [ví dụ: Công nhân sản xuất / Công nhân chế biến gia cầm / Nhân viên kho].", warn: "Phải biết chức danh chính xác như trên I-140 và hợp đồng lao động." },
  { cat: "2", q: "What are your main job duties?", vi: "Nhiệm vụ chính của bạn là gì?", ans: "My main duties include [mô tả công việc cụ thể: ví dụ: processing poultry products on a production line, ensuring quality and maintaining cleanliness standards].", viAns: "Nhiệm vụ chính của tôi là [mô tả: ví dụ: chế biến sản phẩm gia cầm trên dây chuyền sản xuất, đảm bảo chất lượng và vệ sinh].", warn: "Phải mô tả được công việc sẽ làm. Không biết mô tả công việc = red flag lớn." },
  { cat: "2", q: "Does this job require any special skills or experience?", vi: "Công việc này có yêu cầu kỹ năng hoặc kinh nghiệm đặc biệt không?", ans: "No, this is an unskilled position (EB-3 Other Worker). No special education or prior experience is required. The employer provides on-the-job training.", viAns: "Không, đây là vị trí không tay nghề (EB-3 Other Worker). Không yêu cầu bằng cấp hay kinh nghiệm trước đó. Nhà tuyển dụng đào tạo tại chỗ.", tip: "EB-3 EW = unskilled = không yêu cầu kinh nghiệm. Đây là điểm quan trọng phân biệt với EB-3 Skilled." },
  { cat: "2", q: "Have you ever done this type of work before?", vi: "Bạn đã từng làm loại công việc này trước đây chưa?", ans: "[Nếu có] Yes, I have experience in [mô tả kinh nghiệm liên quan] in Vietnam. / [Nếu không] No, but I am willing to learn and the employer will provide training.", viAns: "[Nếu có] Có, tôi có kinh nghiệm về [mô tả] ở Việt Nam. / [Nếu không] Chưa, nhưng tôi sẵn lòng học và nhà tuyển dụng sẽ đào tạo.", tip: "Nếu có kinh nghiệm liên quan, nêu ra. Nếu không có, vẫn ổn — EB-3 EW không yêu cầu." },
  { cat: "2", q: "What safety requirements does your job have?", vi: "Công việc của bạn có yêu cầu an toàn gì?", ans: "The job requires wearing personal protective equipment (PPE) such as [safety gloves, boots, apron, hairnet, eye protection] as required for [food processing/warehouse/manufacturing].", viAns: "Công việc yêu cầu đeo đồ bảo hộ cá nhân (PPE) như [găng tay, ủng, tạp dề, lưới tóc, kính bảo hộ] theo yêu cầu của ngành [chế biến thực phẩm/kho/nhà máy].", tip: "Biết PPE = personal protective equipment. Đây là thuật ngữ hay gặp trong môi trường nhà máy Mỹ." },
  { cat: "2", q: "Who will be your direct supervisor?", vi: "Ai sẽ là người quản lý trực tiếp của bạn?", ans: "My direct supervisor will be the [floor manager / production supervisor] at the facility. I do not know their name yet, but I will find out when I start.", viAns: "Người quản lý trực tiếp của tôi sẽ là [trưởng ca/quản đốc] tại cơ sở. Tôi chưa biết tên cụ thể, sẽ biết khi bắt đầu làm việc.", tip: "Không biết tên supervisor là hoàn toàn bình thường. Không cần biết." },
  { cat: "2", q: "How will you get to work in the US?", vi: "Bạn đi làm bằng cách nào ở Mỹ?", ans: "I plan to purchase a used car once I arrive in the US. In the meantime, I may rely on carpooling with coworkers or public transportation if available.", viAns: "Tôi dự định mua xe cũ khi đến Mỹ. Trong thời gian đầu, có thể đi cùng xe với đồng nghiệp hoặc dùng phương tiện công cộng nếu có.", tip: "Biết xe hơi là cần thiết ở Mỹ. Có kế hoạch rõ ràng là điểm cộng." },
  { cat: "2", q: "What will happen after your 1-year work commitment ends?", vi: "Sau khi hết 1 năm cam kết làm việc, bạn sẽ làm gì?", ans: "After fulfilling my 1-year commitment, I am free to choose my own employment. I may continue with the same employer if both parties agree, or seek other opportunities in my field.", viAns: "Sau khi hoàn thành cam kết 1 năm, tôi tự do lựa chọn việc làm. Có thể tiếp tục với nhà tuyển dụng nếu cả hai bên đồng ý, hoặc tìm cơ hội khác.", tip: "Đây là câu hỏi hợp pháp và câu trả lời này hoàn toàn đúng. Không cần giấu giếm." },
  { cat: "2", q: "Does your job involve working with machinery or equipment?", vi: "Công việc của bạn có liên quan đến máy móc hay thiết bị không?", ans: "Yes/No. [Nếu có]: I will work with [loại máy móc] and will receive proper training before operating any equipment.", viAns: "Có/Không. [Nếu có]: Tôi sẽ làm việc với [loại máy móc] và sẽ được đào tạo đúng cách trước khi vận hành.", tip: "Trả lời thật. Không cần biết chi tiết kỹ thuật — training sẽ được cung cấp khi đến nơi." },
  { cat: "2", q: "What are the physical requirements for this job?", vi: "Yêu cầu thể chất của công việc này là gì?", ans: "The job requires standing for extended periods, lifting up to [ví dụ: 30-50] pounds, and working in a [cold/warm/outdoor] environment. I am in good health and capable of performing these duties.", viAns: "Công việc yêu cầu đứng lâu, nâng đến [30-50] pounds, làm việc trong môi trường [lạnh/ấm/ngoài trời]. Tôi có sức khỏe tốt và đủ khả năng thực hiện.", warn: "Sức khỏe phải phù hợp với công việc. Đây là lý do khám IOM trước phỏng vấn." },

  // CAT 3: Cá Nhân & Gia Đình (10 câu)
  { cat: "3", q: "What is your highest level of education?", vi: "Trình độ học vấn cao nhất của bạn là gì?", ans: "I completed [high school / vocational school / university] in Vietnam. / I graduated from [tên trường] in [năm].", viAns: "Tôi hoàn thành [trung học / trường nghề / đại học] ở Việt Nam.", tip: "EB-3 EW không yêu cầu bằng cấp cao. Dù chỉ tốt nghiệp cấp 3 cũng hoàn toàn ổn." },
  { cat: "3", q: "Are you married? Do you have children?", vi: "Bạn có gia đình chưa? Có con không?", ans: "Yes, I am married to [tên vợ/chồng]. We have [số] children: [tên và tuổi]. They will [travel with me / follow later after I am settled].", viAns: "Vâng, tôi đã kết hôn với [tên]. Chúng tôi có [số] con. Họ sẽ [đi cùng tôi / sang sau khi tôi ổn định].", warn: "Phải nhất quán với thông tin trên DS-260. Nếu gia đình không đi cùng, giải thích lý do rõ ràng." },
  { cat: "3", q: "Does anyone in your family already live in the United States?", vi: "Có ai trong gia đình bạn đang sống ở Mỹ không?", ans: "[Nếu có] Yes, I have [quan hệ] living in [thành phố, tiểu bang]. / [Nếu không] No, I do not have family in the United States.", viAns: "[Nếu có] Có, tôi có [người thân] đang sống ở [thành phố, tiểu bang]. / [Nếu không] Không.", tip: "Trả lời thật. Có người thân ở Mỹ không phải là điều xấu — thực ra có thể là điểm cộng (có chỗ dựa khi mới sang)." },
  { cat: "3", q: "Have you ever been to the United States before?", vi: "Bạn đã từng đến Mỹ trước đây chưa?", ans: "[Nếu chưa] No, this will be my first time visiting the United States. / [Nếu có] Yes, I visited the US in [năm] on a [tourist/student] visa and returned to Vietnam as required.", viAns: "[Nếu chưa] Chưa, đây sẽ là lần đầu tiên tôi đến Mỹ. / [Nếu có] Có, tôi đến Mỹ năm [năm] với visa [du lịch/học sinh] và về VN đúng hạn.", warn: "Nếu từng quá hạn visa hoặc vi phạm — phải khai báo trung thực. Giấu = có thể bị cấm nhập cảnh vĩnh viễn." },
  { cat: "3", q: "Have you ever been arrested or convicted of a crime?", vi: "Bạn có từng bị bắt hoặc bị kết tội hình sự không?", ans: "No, I have no criminal record. My legal background check (Criminal Background Certificate) is clean.", viAns: "Không, tôi không có tiền án tiền sự. Lý lịch tư pháp của tôi sạch.", warn: "Câu này PHẢI trả lời thật. Nếu có — khai báo và tham khảo luật sư. Che giấu = từ chối vĩnh viễn." },
  { cat: "3", q: "Have you ever been denied a US visa before?", vi: "Bạn đã từng bị từ chối visa Mỹ trước đây chưa?", ans: "[Nếu chưa] No, I have never applied for or been denied a US visa before. / [Nếu có] Yes, I was denied a [loại] visa in [năm] because [lý do]. Since then, [giải thích thay đổi].", viAns: "[Nếu chưa] Chưa. / [Nếu có] Có, tôi bị từ chối visa [loại] năm [năm] vì [lý do].", warn: "Phải khai báo trung thực. Từ chối visa trước không tự động loại bạn — nhưng giấu thì có thể bị cấm." },
  { cat: "3", q: "What have you been doing for work in Vietnam?", vi: "Bạn đang làm gì ở Việt Nam?", ans: "I have been working as a [công việc] in Vietnam for [số] years. My work experience is in [ngành].", viAns: "Tôi đã làm [công việc] ở Việt Nam được [số] năm. Kinh nghiệm của tôi trong ngành [ngành].", tip: "Không cần kinh nghiệm liên quan đến công việc EB-3 — EB-3 EW là unskilled. Cứ nói thật công việc hiện tại." },
  { cat: "3", q: "Do you speak English?", vi: "Bạn có nói được tiếng Anh không?", ans: "I speak [a little / basic / intermediate] English. I am currently studying English and will continue to improve after arriving in the US.", viAns: "Tôi nói được [một ít / cơ bản / khá] tiếng Anh. Tôi đang học và sẽ tiếp tục cải thiện sau khi sang Mỹ.", tip: "Không cần tiếng Anh giỏi để được visa EB-3. Thành thật về trình độ thực tế là tốt nhất." },
  { cat: "3", q: "Do you intend to remain in the US permanently?", vi: "Bạn có ý định ở lại Mỹ vĩnh viễn không?", ans: "Yes. The purpose of EB-3 is permanent immigration. I intend to work, live, and potentially become a US citizen in the future.", viAns: "Vâng. Mục đích của EB-3 là định cư vĩnh viễn. Tôi dự định làm việc, sinh sống và có thể trở thành công dân Mỹ trong tương lai.", tip: "EB-3 là visa định cư vĩnh viễn — phải thể hiện ý định ở lại lâu dài. Khác với visa du lịch phải chứng minh sẽ về." },
  { cat: "3", q: "Are you in good health and able to perform the job duties?", vi: "Bạn có sức khỏe tốt và đủ khả năng thực hiện công việc không?", ans: "Yes, I am in good health. I have completed my medical examination with IOM-approved doctors and my results show I meet all health requirements.", viAns: "Vâng, tôi có sức khỏe tốt. Tôi đã khám IOM và kết quả đáp ứng tất cả yêu cầu sức khỏe.", warn: "Đây là lý do khám sức khỏe IOM bắt buộc trước phỏng vấn." },

  // CAT 4: Kế Hoạch Ở Mỹ (10 câu)
  { cat: "4", q: "Where will you live when you arrive in the US?", vi: "Bạn sẽ ở đâu khi đến Mỹ?", ans: "I plan to live near [thành phố/tiểu bang làm việc]. I have researched housing options in the area and will secure accommodation before or shortly after arrival.", viAns: "Tôi dự định sống gần [thành phố/bang làm việc]. Tôi đã tìm hiểu các lựa chọn nhà ở và sẽ sắp xếp chỗ ở trước hoặc ngay sau khi đến.", tip: "Tốt nhất là đã tìm hiểu trước về khu vực sẽ sống. Cho thấy bạn chuẩn bị nghiêm túc." },
  { cat: "4", q: "Do you have enough money to support yourself when you first arrive?", vi: "Bạn có đủ tiền để tự nuôi sống bản thân khi mới sang Mỹ không?", ans: "Yes, I have saved approximately $[số tiền] USD to cover initial expenses including housing, transportation, and daily living costs until I receive my first paycheck.", viAns: "Vâng, tôi đã tiết kiệm khoảng $[số tiền] USD để chi phí ban đầu bao gồm nhà ở, đi lại và sinh hoạt cho đến khi nhận lương đầu tiên.", tip: "Chuẩn bị ít nhất $3,000-5,000 USD. Đây là mức an toàn cho 1-2 tháng đầu." },
  { cat: "4", q: "How do you plan to travel to the US?", vi: "Bạn dự định đi đến Mỹ như thế nào?", ans: "I will travel by international flight from [sân bay VN] to the nearest major airport to my workplace in [thành phố, tiểu bang].", viAns: "Tôi sẽ bay quốc tế từ [sân bay VN] đến sân bay gần nơi làm việc nhất ở [thành phố, tiểu bang].", tip: "Biết sân bay đến gần công ty là điểm cộng — cho thấy đã chuẩn bị cụ thể." },
  { cat: "4", q: "Will your family join you? When?", vi: "Gia đình bạn có sang cùng không? Khi nào?", ans: "Yes, my [vợ/chồng] and [số con] children will travel with me at the same time. / My family will join me after I have settled in, approximately [thời gian] months later.", viAns: "Vâng, [vợ/chồng] và [số] con sẽ đi cùng tôi. / Gia đình sẽ sang sau khi tôi ổn định, khoảng [thời gian] tháng sau.", tip: "Nhất quán với thông tin trên DS-260 và hồ sơ." },
  { cat: "4", q: "What are your long-term plans in the United States?", vi: "Kế hoạch lâu dài của bạn ở Mỹ là gì?", ans: "My long-term plans are to work hard, learn English, build a stable life for my family, and contribute to my community. After 5 years, I plan to apply for US citizenship.", viAns: "Kế hoạch lâu dài là làm việc chăm chỉ, học tiếng Anh, xây dựng cuộc sống ổn định cho gia đình và đóng góp cho cộng đồng. Sau 5 năm, tôi dự định thi quốc tịch Mỹ.", tip: "Thể hiện kế hoạch lâu dài và nghiêm túc. Tránh nói \"kiếm tiền rồi về VN\" — điều đó mâu thuẫn với visa định cư." },
  { cat: "4", q: "Do you know anyone in the city where you will be working?", vi: "Bạn có quen biết ai ở thành phố sẽ làm việc không?", ans: "[Nếu có] Yes, I know [người] who lives in [thành phố]. / [Nếu không] No, but I plan to connect with the Vietnamese community there and with my coworkers.", viAns: "[Nếu có] Có, tôi quen [người] sống ở [thành phố]. / [Nếu không] Không, nhưng tôi dự định kết nối với cộng đồng người Việt và đồng nghiệp.", tip: "Có người quen ở địa phương là điểm cộng — cho thấy có mạng lưới hỗ trợ." },
  { cat: "4", q: "What will you do if the job doesn't work out?", vi: "Bạn sẽ làm gì nếu công việc không thuận lợi?", ans: "I am committed to fulfilling my 1-year work agreement with the sponsor. After that, as a permanent resident, I have the right to seek other employment opportunities in the US.", viAns: "Tôi cam kết thực hiện đúng hợp đồng 1 năm với nhà tuyển dụng. Sau đó, với tư cách thường trú nhân, tôi có quyền tìm việc khác ở Mỹ.", tip: "Thể hiện cam kết trước, quyền lợi sau — thứ tự này quan trọng." },
  { cat: "4", q: "How will your children attend school in the US?", vi: "Con cái bạn sẽ học ở Mỹ như thế nào?", ans: "My children will attend public school (K-12) in the area where we live. Public school is free for all permanent residents. I will enroll them within the required timeframe after arrival.", viAns: "Con tôi sẽ học trường công lập (K-12) gần nơi ở. Trường công miễn học phí cho thường trú nhân. Tôi sẽ đăng ký trong thời hạn quy định sau khi đến.", tip: "Trường công (public school) K-12 miễn phí cho con thường trú nhân — đây là quyền lợi lớn." },
  { cat: "4", q: "What do you know about the city where you will be working?", vi: "Bạn biết gì về thành phố nơi bạn sẽ làm việc?", ans: "I have researched [thành phố]. I know it is located in [tiểu bang], has a cost of living of approximately [chi phí], and has a Vietnamese community in the area.", viAns: "Tôi đã tìm hiểu về [thành phố]. Tôi biết nó nằm ở [tiểu bang], chi phí sinh hoạt khoảng [số tiền]/tháng, và có cộng đồng người Việt.", tip: "Cho thấy bạn đã chuẩn bị nghiêm túc — không phải bốc đồng xin visa." },
  { cat: "4", q: "What will you do after becoming a US permanent resident?", vi: "Sau khi trở thành thường trú nhân Mỹ, bạn sẽ làm gì?", ans: "I plan to work hard, pay taxes, learn English, and eventually apply for US citizenship after 5 years. I want to give my family a better future.", viAns: "Tôi dự định làm việc chăm chỉ, đóng thuế, học tiếng Anh và cuối cùng xin quốc tịch Mỹ sau 5 năm. Tôi muốn cho gia đình tương lai tốt hơn.", tip: "Câu trả lời đúng tinh thần của chương trình EB-3." },

  // CAT 5: Hồ Sơ & Pháp Lý (10 câu)
  { cat: "5", q: "Do you have your employment contract with you?", vi: "Bạn có mang theo hợp đồng lao động không?", ans: "Yes, I have my employment contract with me [or: in my document package]. It includes details about my job title, duties, salary, and work location.", viAns: "Vâng, tôi có mang theo hợp đồng lao động. Nó bao gồm chức danh, nhiệm vụ, lương và địa điểm làm việc.", warn: "PHẢI mang đầy đủ giấy tờ theo danh sách LSQ. Thiếu giấy tờ = có thể bị 221g." },
  { cat: "5", q: "Can you explain what an I-140 is?", vi: "Bạn có thể giải thích I-140 là gì không?", ans: "The I-140 is the Immigrant Petition for Alien Workers. My employer filed it with USCIS to prove they can financially support my employment and that our employment relationship is genuine.", viAns: "I-140 là đơn bảo lãnh người nước ngoài theo diện việc làm. Nhà tuyển dụng nộp lên USCIS để chứng minh khả năng tài chính và mối quan hệ lao động thật sự.", tip: "Biết tên I-140 là gì = cho thấy bạn hiểu hồ sơ của mình." },
  { cat: "5", q: "What is your Priority Date?", vi: "Priority Date (Ngày ưu tiên) của bạn là gì?", ans: "My Priority Date is [ngày/tháng/năm]. This is the date the Department of Labor received my Labor Certification application.", viAns: "Ngày ưu tiên của tôi là [ngày/tháng/năm]. Đây là ngày Bộ Lao Động nhận đơn LC của tôi.", warn: "Phải biết Priority Date chính xác. Đây là ngày quan trọng nhất trong hồ sơ." },
  { cat: "5", q: "Have you ever overstayed a visa in any country?", vi: "Bạn đã từng quá hạn visa ở bất kỳ quốc gia nào không?", ans: "No, I have always respected visa regulations in every country I have visited and left on time as required.", viAns: "Không, tôi luôn tuân thủ quy định visa ở mọi quốc gia đã đến và rời đúng hạn.", warn: "Nếu có quá hạn — PHẢI khai báo. Đặc biệt nếu từng ở Mỹ bất hợp pháp — ảnh hưởng rất nghiêm trọng." },
  { cat: "5", q: "Do you have any outstanding debts or financial obligations?", vi: "Bạn có khoản nợ nào chưa thanh toán không?", ans: "[Nếu không] No significant debts. / [Nếu có khoản vay làm hồ sơ] I have a personal loan for immigration-related expenses which I am repaying.", viAns: "[Nếu không] Không có nợ đáng kể. / [Nếu vay tiền làm hồ sơ] Tôi có khoản vay cá nhân cho chi phí di trú đang trả.", warn: "Vay tiền để làm hồ sơ EB-3 không xấu về mặt pháp lý nhưng tránh nói \"phải vay mới làm được\" — cho thấy không đủ tài chính." },
  { cat: "5", q: "Are all the documents you submitted truthful and accurate?", vi: "Tất cả giấy tờ bạn nộp có trung thực và chính xác không?", ans: "Yes, all documents I submitted are truthful and accurate to the best of my knowledge. I understand that misrepresentation is grounds for permanent inadmissibility.", viAns: "Vâng, tất cả giấy tờ tôi nộp đều trung thực và chính xác. Tôi hiểu rằng khai gian = có thể bị cấm nhập cảnh vĩnh viễn.", warn: "Đây là cam kết pháp lý quan trọng. Nếu phát hiện gian dối — hậu quả rất nghiêm trọng." },
  { cat: "5", q: "Do you understand the terms of your EB-3 sponsorship?", vi: "Bạn có hiểu các điều khoản bảo trợ EB-3 của mình không?", ans: "Yes. I understand I must work for the sponsoring employer for at least 1 year, comply with US laws, file taxes annually, and fulfill my immigration obligations.", viAns: "Vâng. Tôi hiểu phải làm việc cho nhà tuyển dụng ít nhất 1 năm, tuân thủ luật Mỹ, khai thuế hàng năm, và thực hiện nghĩa vụ di trú.", tip: "Cho thấy bạn không chỉ muốn visa mà thực sự hiểu nghĩa vụ của mình." },
  { cat: "5", q: "Have you ever been deported from or denied entry to any country?", vi: "Bạn đã từng bị trục xuất hoặc bị từ chối nhập cảnh ở bất kỳ quốc gia nào chưa?", ans: "No, I have never been deported or denied entry to any country.", viAns: "Không, tôi chưa bao giờ bị trục xuất hoặc từ chối nhập cảnh ở bất kỳ quốc gia nào.", warn: "PHẢI khai báo trung thực. Giấu thông tin này = lý do từ chối vĩnh viễn." },
  { cat: "5", q: "Is there anything in your background that might affect your visa application?", vi: "Có điều gì trong lý lịch của bạn có thể ảnh hưởng đến đơn xin visa không?", ans: "No, I do not believe there is anything in my background that would affect my application. I have a clean criminal record and have always complied with visa regulations.", viAns: "Không, tôi không nghĩ có điều gì trong lý lịch ảnh hưởng đến đơn xin. Tôi có lý lịch tư pháp sạch và luôn tuân thủ quy định visa.", warn: "Nếu có bất kỳ vấn đề nào — khai báo và chuẩn bị giải thích với sự hỗ trợ của luật sư." },
  { cat: "5", q: "What will you do if your visa is denied?", vi: "Bạn sẽ làm gì nếu visa bị từ chối?", ans: "If denied, I would consult with my attorney and immigration agency to understand the reason, and if grounds exist, file an appeal or reapplication. I am committed to following the legal process.", viAns: "Nếu bị từ chối, tôi sẽ tham khảo luật sư và agency để hiểu lý do, và nếu có cơ sở, sẽ kháng cáo hoặc nộp lại. Tôi cam kết theo quy trình pháp lý.", tip: "Câu trả lời này cho thấy sự trưởng thành và hiểu biết về quy trình. Tránh tỏ ra tức giận hoặc thất vọng." },
];
