import type { QuizQuestion } from "../components/bmv-quiz-engine";

export const NC_PASS_COUNT = 30;

export const NC_QUESTIONS: QuizQuestion[] = [
  {en:"What is the default speed limit in a North Carolina city or town?",vi:"Giới hạn tốc độ mặc định trong thành phố/thị trấn North Carolina?",opts:[{en:"25 mph",vi:"25 mph"},{en:"30 mph",vi:"30 mph"},{en:"35 mph",vi:"35 mph"},{en:"45 mph",vi:"45 mph"}],ans:2,exp:{en:"The default speed limit in North Carolina urban areas (cities and towns) is 35 mph unless otherwise posted.",vi:"Tốc độ mặc định khu đô thị NC là 35 mph trừ khi có biển báo khác."}},
  {en:"North Carolina refers to impaired driving as:",vi:"North Carolina gọi lái xe say rượu là gì?",opts:[{en:"DUI",vi:"DUI"},{en:"DWI — Driving While Impaired",vi:"DWI — Driving While Impaired"},{en:"OWI",vi:"OWI"},{en:"BWI",vi:"BWI"}],ans:1,exp:{en:"North Carolina uses the term DWI (Driving While Impaired). A BAC of 0.08% or higher is illegal.",vi:"North Carolina dùng DWI (Driving While Impaired). BAC ≥0.08% là phạm pháp."}},
  {en:"In North Carolina, motorcycle helmets are:",vi:"Ở North Carolina, mũ bảo hiểm xe máy:",opts:[{en:"Optional for adults 21+",vi:"Optional for adults 21+"},{en:"Not required for licensed riders",vi:"Not required for licensed riders"},{en:"Required for all motorcycle riders and passengers",vi:"Required for all motorcycle riders and passengers"},{en:"Only required on highways",vi:"Only required on highways"}],ans:2,exp:{en:"North Carolina law requires ALL motorcycle riders and passengers to wear helmets, regardless of age.",vi:"NC bắt buộc TẤT CẢ người lái và hành khách xe máy đội mũ bảo hiểm, bất kể tuổi."}},
  {en:"What is the speed limit in a North Carolina school zone when children are present?",vi:"Giới hạn tốc độ khu trường học NC khi có trẻ em?",opts:[{en:"15 mph",vi:"15 mph"},{en:"20 mph",vi:"20 mph"},{en:"25 mph",vi:"25 mph"},{en:"30 mph",vi:"30 mph"}],ans:2,exp:{en:"North Carolina school zones have a speed limit of 25 mph when the flashing lights are active or when children are present.",vi:"Khu trường học NC: 25 mph khi đèn nhấp nháy hoặc có trẻ em."}},
  {en:"In North Carolina, which drivers are prohibited from using a cell phone?",vi:"Ở NC, tài xế nào bị cấm dùng điện thoại?",opts:[{en:"All drivers under 21",vi:"All drivers under 21"},{en:"Drivers under 18 are banned from all phone use; all drivers banned from texting",vi:"Drivers under 18 are banned from all phone use; all drivers banned from texting"},{en:"Only commercial drivers",vi:"Only commercial drivers"},{en:"No restrictions",vi:"No restrictions"}],ans:1,exp:{en:"NC: Drivers under 18 may not use a cell phone at all while driving. ALL drivers may not text or read/send messages.",vi:"NC: Dưới 18t cấm dùng điện thoại hoàn toàn. Tất cả tài xế không được texting."}},
  {en:"What is the BAC limit for drivers under 21 in North Carolina?",vi:"Giới hạn BAC cho tài xế dưới 21 tuổi ở NC?",opts:[{en:"0.08%",vi:"0.08%"},{en:"0.04%",vi:"0.04%"},{en:"0.02%",vi:"0.02%"},{en:"Any amount is illegal",vi:"Any amount is illegal"}],ans:3,exp:{en:"North Carolina has zero tolerance for drivers under 21 — any detectable BAC results in a DWI charge.",vi:"NC zero-tolerance dưới 21 tuổi — bất kỳ BAC nào phát hiện được là DWI."}},
  {en:"What is the default speed limit on North Carolina interstates?",vi:"Giới hạn tốc độ mặc định trên interstate NC?",opts:[{en:"55 mph",vi:"55 mph"},{en:"60 mph",vi:"60 mph"},{en:"65 mph",vi:"65 mph"},{en:"70 mph",vi:"70 mph"}],ans:3,exp:{en:"North Carolina interstate highways have a default speed limit of 70 mph for passenger vehicles.",vi:"Interstate NC có giới hạn mặc định 70 mph cho xe hơi thông thường."}},
  {en:"When must you stop for a school bus in North Carolina?",vi:"Khi nào phải dừng cho xe buýt trường học ở NC?",opts:[{en:"Only when behind it",vi:"Only when behind it"},{en:"When its red lights are flashing, in all directions unless separated by a median",vi:"When its red lights are flashing, in all directions unless separated by a median"},{en:"Only in the same direction",vi:"Only in the same direction"},{en:"Slow to 15 mph and proceed",vi:"Slow to 15 mph and proceed"}],ans:1,exp:{en:"You must stop in both directions when a school bus has flashing red lights, unless a median or physical barrier separates traffic.",vi:"Phải dừng cả 2 chiều khi đèn đỏ nhấp nháy, trừ khi có dải phân cách hoặc rào chắn."}},
  {en:"In North Carolina, what must you do when an emergency vehicle approaches?",vi:"Ở NC, phải làm gì khi xe cứu thương tiến lại?",opts:[{en:"Speed up to clear the way",vi:"Speed up to clear the way"},{en:"Pull to the right and stop until the vehicle passes",vi:"Pull to the right and stop until the vehicle passes"},{en:"Stay in your lane",vi:"Stay in your lane"},{en:"Move left",vi:"Move left"}],ans:1,exp:{en:"Pull to the right side of the road and stop until all emergency vehicles have passed.",vi:"Kéo vào lề phải và dừng cho đến khi tất cả xe cứu thương qua hết."}},
  {en:"What is the minimum following distance recommended in NC?",vi:"Khoảng cách theo sau tối thiểu khuyến nghị ở NC?",opts:[{en:"1 second",vi:"1 second"},{en:"2 seconds",vi:"2 seconds"},{en:"3 seconds",vi:"3 seconds"},{en:"4 seconds",vi:"4 seconds"}],ans:2,exp:{en:"North Carolina recommends a minimum 3-second following distance in normal conditions, more in bad weather.",vi:"NC khuyến nghị tối thiểu 3 giây trong điều kiện bình thường, nhiều hơn khi thời tiết xấu."}},
  {en:"Can you turn right on red in North Carolina?",vi:"Có được rẽ phải khi đèn đỏ ở NC không?",opts:[{en:"Never",vi:"Never"},{en:"Yes, after stopping completely and yielding, unless prohibited by a sign",vi:"Yes, after stopping completely and yielding, unless prohibited by a sign"},{en:"Only with a green arrow",vi:"Only with a green arrow"},{en:"Yes, without stopping",vi:"Yes, without stopping"}],ans:1,exp:{en:"Right on red is permitted in NC after a complete stop and yielding to traffic and pedestrians, unless a sign prohibits it.",vi:"Được rẽ phải khi đèn đỏ sau khi dừng hoàn toàn và nhường đường, trừ khi có biển cấm."}},
  {en:"What does a solid yellow center line mean?",vi:"Vạch vàng liền ở giữa đường có nghĩa là gì?",opts:[{en:"Passing allowed from that side",vi:"Passing allowed from that side"},{en:"No passing from that side",vi:"No passing from that side"},{en:"Speed limit change",vi:"Speed limit change"},{en:"Construction zone",vi:"Construction zone"}],ans:1,exp:{en:"A solid yellow line on YOUR side means you cannot pass. A dashed yellow allows passing when safe.",vi:"Vạch vàng liền ở phía BẠN = không được vượt. Vạch đứt = được vượt khi an toàn."}},
  {en:"In North Carolina, seat belts are required for:",vi:"Dây an toàn ở NC bắt buộc cho:",opts:[{en:"Only front seat occupants",vi:"Only front seat occupants"},{en:"Driver and all passengers in any seating position",vi:"Driver and all passengers in any seating position"},{en:"Only occupants under 16",vi:"Only occupants under 16"},{en:"Only the driver",vi:"Only the driver"}],ans:1,exp:{en:"NC law requires ALL vehicle occupants to wear seat belts regardless of their seating position.",vi:"Luật NC: TẤT CẢ người trong xe phải thắt dây an toàn bất kể ngồi ở đâu."}},
  {en:"What is NC's law about using headlights?",vi:"Luật về đèn pha ở NC?",opts:[{en:"Only at night",vi:"Only at night"},{en:"Required from 30 minutes after sunset to 30 minutes before sunrise, and during rain or limited visibility",vi:"Required from 30 minutes after sunset to 30 minutes before sunrise, and during rain or limited visibility"},{en:"Only in heavy rain",vi:"Only in heavy rain"},{en:"Only on highways",vi:"Only on highways"}],ans:1,exp:{en:"NC requires headlights from 30 minutes after sunset to 30 minutes before sunrise, and whenever windshield wipers are in use.",vi:"NC: bật đèn từ 30 phút sau hoàng hôn đến 30 phút trước bình minh, và khi dùng gạt nước."}},
  {en:"At an uncontrolled intersection in NC, who has right-of-way?",vi:"Tại giao lộ không kiểm soát ở NC, ai có quyền ưu tiên?",opts:[{en:"Vehicle on the left",vi:"Vehicle on the left"},{en:"Vehicle that arrived first; if simultaneous, vehicle on the right",vi:"Vehicle that arrived first; if simultaneous, vehicle on the right"},{en:"Larger vehicle",vi:"Larger vehicle"},{en:"Faster vehicle",vi:"Faster vehicle"}],ans:1,exp:{en:"At uncontrolled intersections, the vehicle that arrived first has right-of-way. If simultaneous, yield to the vehicle on your right.",vi:"Giao lộ không kiểm soát: ai đến trước đi trước. Nếu cùng lúc, nhường xe ở bên phải."}},
  {en:"What are the minimum liability insurance requirements in NC?",vi:"Yêu cầu bảo hiểm trách nhiệm tối thiểu ở NC?",opts:[{en:"$10,000/$20,000/$5,000",vi:"$10,000/$20,000/$5,000"},{en:"$25,000/$50,000/$25,000",vi:"$25,000/$50,000/$25,000"},{en:"$30,000/$60,000/$25,000",vi:"$30,000/$60,000/$25,000"},{en:"No minimum",vi:"No minimum"}],ans:1,exp:{en:"North Carolina requires minimum liability: $30,000 per person / $60,000 per accident / $25,000 property damage.",vi:"NC yêu cầu tối thiểu: $30,000/người · $60,000/tai nạn · $25,000 hư hại tài sản."}},
  {en:"What does a flashing yellow light mean?",vi:"Đèn vàng nhấp nháy có nghĩa là gì?",opts:[{en:"Stop completely",vi:"Stop completely"},{en:"Proceed with caution — slow down",vi:"Proceed with caution — slow down"},{en:"Speed up to clear",vi:"Speed up to clear"},{en:"Emergency vehicle ahead",vi:"Emergency vehicle ahead"}],ans:1,exp:{en:"A flashing yellow light means slow down and proceed with caution. You do not need to stop.",vi:"Đèn vàng nhấp nháy: giảm tốc và đi qua thận trọng. Không cần dừng hoàn toàn."}},
  {en:"In NC, when following a vehicle, what is the safest rule?",vi:"Ở NC, khi đi theo xe khác, quy tắc an toàn nhất?",opts:[{en:"Stay as close as possible",vi:"Stay as close as possible"},{en:"Use the 3-second rule — pick a fixed point and count to 3 after the car ahead passes it",vi:"Use the 3-second rule — pick a fixed point and count to 3 after the car ahead passes it"},{en:"Stay 10 car lengths back",vi:"Stay 10 car lengths back"},{en:"Match the speed of surrounding traffic",vi:"Match the speed of surrounding traffic"}],ans:1,exp:{en:"The 3-second rule: choose a fixed landmark, when the car ahead passes it, count to 3. Your car should not reach that point yet.",vi:"Quy tắc 3 giây: chọn điểm cố định, khi xe trước qua đó đếm đến 3. Xe bạn chưa được đến điểm đó."}},
  {en:"What is the NC Move Over Law?",vi:"Luật Move Over NC là gì?",opts:[{en:"Move right on all roads",vi:"Move right on all roads"},{en:"Move over a lane or slow down significantly when passing stopped emergency, tow, or utility vehicles on the roadside",vi:"Move over a lane or slow down significantly when passing stopped emergency, tow, or utility vehicles on the roadside"},{en:"Stop completely",vi:"Stop completely"},{en:"Only for police cars",vi:"Only for police cars"}],ans:1,exp:{en:"NC's Move Over Law requires changing lanes or significantly reducing speed when passing emergency, law enforcement, or public service vehicles stopped on the roadside.",vi:"Luật Move Over NC: chuyển làn hoặc giảm tốc đáng kể khi qua xe cứu thương/cảnh sát/tiện ích dừng ven đường."}},
  {en:"Which sign has a pentagon (5-sided) shape?",vi:"Biển nào có hình ngũ giác (5 cạnh)?",opts:[{en:"Railroad crossing",vi:"Railroad crossing"},{en:"School zone / school crossing",vi:"School zone / school crossing"},{en:"Speed limit",vi:"Speed limit"},{en:"Construction zone",vi:"Construction zone"}],ans:1,exp:{en:"The pentagon-shaped sign is exclusively used for school zone and school crossing warning signs.",vi:"Biển hình ngũ giác chỉ dùng cho biển cảnh báo khu trường học và lối sang đường trường học."}},
  {en:"In NC, how far before a turn must you signal?",vi:"Ở NC, phải bật xi-nhan trước khi rẽ bao xa?",opts:[{en:"25 feet",vi:"25 feet"},{en:"50 feet",vi:"50 feet"},{en:"100 feet",vi:"100 feet"},{en:"At the intersection",vi:"At the intersection"}],ans:2,exp:{en:"North Carolina requires signaling at least 100 feet before making a turn or changing lanes.",vi:"NC yêu cầu bật xi-nhan ít nhất 100 feet trước khi rẽ hoặc đổi làn."}},
];
