/**
 * FAQ dataset ported from faq.html's inline `FAQS` array (legacy lines 482-511).
 * Kept as a standalone data module so faq-content.tsx stays under the
 * 200-line guideline.
 */
export type FaqCategory =
  | "chung"
  | "agency"
  | "quy-trinh"
  | "tai-chinh"
  | "cspa"
  | "life";

export interface FaqItem {
  cat: FaqCategory;
  q: string;
  a: string;
}

export const FAQ_CATEGORIES: Array<{ key: FaqCategory | "all"; label: string }> = [
  { key: "all", label: "Tất cả" },
  { key: "chung", label: "Tổng quan" },
  { key: "agency", label: "Agency" },
  { key: "quy-trinh", label: "Quy trình" },
  { key: "tai-chinh", label: "Chi phí" },
  { key: "cspa", label: "Con cái / CSPA" },
  { key: "life", label: "Cuộc sống Mỹ" },
];

export const FAQS: FaqItem[] = [
  { cat: "chung", q: "EB-3 là gì? Khác gì các diện định cư khác?", a: "<b>EB-3 (Employment-Based Third Preference)</b> là chương trình lao động định cư Mỹ cho người nước ngoài, được Quốc Hội Mỹ phê chuẩn từ 1990. Có 3 loại: chuyên gia (professional), tay nghề (skilled), và <em>không tay nghề (unskilled / Other Workers — EW)</em> — phần này chủ yếu nói về diện EW. Không yêu cầu bằng cấp hay kinh nghiệm chuyên môn. Khác với diện bảo lãnh thân nhân (F), đây là diện lao động — cần nhà tuyển dụng Mỹ bảo trợ." },
  { cat: "chung", q: "Tại sao Mỹ cần lao động EB-3?", a: "Mỹ thiếu lao động phổ thông do dân số già hóa. Nhiều công việc như chế biến thực phẩm, kho bãi, hộ lý, nhà máy... người Mỹ không muốn làm vì lương thấp và điều kiện vất vả. Công nhân trong nước nghỉ việc nhiều, khiến doanh nghiệp mất ổn định. <em>EB-3 là nguồn nhân công hợp pháp, gắn bó lâu dài</em>." },
  { cat: "chung", q: "Quyền lợi khi có thẻ xanh EB-3 là gì?", a: "<b>Quyền lợi chính:</b> Thẻ xanh 10 năm (Permanent Resident) cho cả gia đình; sau 5 năm ở Mỹ được thi quốc tịch; con dưới 18t tự động được quốc tịch khi cha/mẹ thi đậu; con học miễn phí K-12; được hoàn thuế Child Tax Credit (~$2,000–3,600/con); học tiếng Anh miễn phí (ESL); bảo hiểm y tế. <b>Trách nhiệm:</b> Làm việc cho hãng bảo trợ tối thiểu 1 năm; khai thuế hàng năm; tuân thủ luật pháp Mỹ." },
  { cat: "chung", q: "Điều kiện để tham gia EB-3 là gì?", a: "<em>Độ tuổi:</em> 18–50 (một số hãng nhận đến 55t). <em>Lý lịch:</em> Trong sạch, không tiền án (đặc biệt về ma túy, lừa đảo di trú). <em>Sức khỏe:</em> Đủ khả năng lao động, không mắc bệnh truyền nhiễm trong danh sách CDC. <em>Vaccine:</em> Tiêm đầy đủ theo yêu cầu USCIS. <em>Tài chính:</em> Đủ khả năng tự nuôi sống sau khi định cư, không thành gánh nặng xã hội." },
  { cat: "chung", q: "Những ai KHÔNG nên làm hồ sơ EB-3?", a: "Không nên làm nếu: Sức khỏe kém / bệnh mãn tính; phải vay mượn bán nhà để nộp phí; có tiền án tiền sự (dù đã xóa — vẫn rủi ro cao); đảng viên (hạn chế); nghiện ngập; từng cư trú bất hợp pháp ở nước ngoài; <em>không kiên nhẫn — hiện chờ 7–9 năm</em>; không có ý định đi làm thật sau khi có thẻ xanh." },
  { cat: "chung", q: "EB-3 có phải lừa đảo không?", a: "<b>Không</b> — EB-3 là chương trình có thật, được Quốc Hội Mỹ phê chuẩn. <em>Lừa đảo là người lợi dụng EB-3 để trục lợi</em> — agency thu tiền rồi không giao case number, sponsor giả, thông tin sai lệch. Bạn có thể kiểm tra visa EW được cấp hàng tháng tại trang Visa Issuance Statistics của DOS." },
  { cat: "chung", q: "Chính sách nhập cư mới của Trump ảnh hưởng thế nào đến EB-3?", a: "EB-3 là diện lao động định cư hợp pháp được quy định bởi Đạo luật Di trú và Quốc tịch (INA). <em>Chỉ Quốc hội mới có quyền xóa bỏ EB-3</em> — Tổng thống không thể đơn phương. Tuy nhiên, chính quyền Trump đang: tăng cường kiểm tra ICE, siết nhập cư BHP, tăng thẩm tra hồ sơ (có thể làm chậm). Chính sách 2025 có thể ảnh hưởng chuyển diện nhiều hơn truyền thống. Cập nhật 06/2025: EB-3 vẫn tiếp tục, chưa có thay đổi lớn." },
  { cat: "chung", q: "Tổng thời gian hồ sơ EB-3 từ đầu đến có thẻ xanh là bao lâu?", a: "Phụ thuộc nhiều yếu tố. <em>Ước tính hiện tại (2025):</em> Hồ sơ mở năm 2023: ~5–6 năm. Mở 2024: ~7 năm. Mở 2025: ~8 năm. Đây chỉ là dự báo — Visa Bulletin, quota, hãng bảo trợ và agency đều ảnh hưởng đến timeline thực tế." },
  { cat: "chung", q: "EB-3 chỉ tốn thời gian chờ, còn chắc chắn đi được không?", a: "<b>Không chắc chắn</b>. Có nhiều rủi ro: hãng bảo trợ phá sản; agency gian dối; hồ sơ bị từ chối LC/I-140; phỏng vấn rớt; quota cạn; lý lịch có vấn đề. <em>Mở hồ sơ không = đảm bảo đi được</em>. Cần chọn agency tốt, chuẩn bị kỹ và hiểu rõ hồ sơ của mình." },
  { cat: "tai-chinh", q: "Chi phí EB-3 gồm những khoản nào?", a: "<b>3 khoản chính:</b><br>① <em>Phí dịch vụ agency:</em> 20–45k USD (mình khuyến nghị 20–30k là hợp lý)<br>② <em>Phí chính phủ:</em> I-140: $1,315; DS-260: $345/người; thẻ xanh: $235/người; sinh trắc: $85/người; khám sức khỏe: ~$240 người lớn. Tổng ~$3,000/đương đơn<br>③ <em>Chi phí khi mới sang Mỹ:</em> Xe cũ: $10,000+; thuê nhà: $700–2,000/tháng; sinh hoạt tháng đầu: $2,000–4,000" },
  { cat: "tai-chinh", q: "Tại sao có sự chênh lệch giá lớn giữa các agency?", a: "Phí phụ thuộc vào: phí luật sư Mỹ (quan trọng nhất), nhân sự chuyên môn, ngành nghề và bang làm việc, phí đã bao gồm phí chính phủ chưa, số cầu qua bao nhiêu tầng trung gian (F2, F3 sẽ tăng phí x2–x3). <em>Đắt không có nghĩa là tốt hơn</em> — quan trọng là hiểu mình trả tiền cho gì và được gì." },
  { cat: "tai-chinh", q: "Hiện có nơi yêu cầu đóng 5k USD để làm hồ sơ, qua Mỹ đóng phần còn lại. Có đúng không?", a: "<b>Không có agency đàng hoàng nào làm vậy.</b> Đây là chiêu lừa đảo phổ biến — thu 5k đặt cọc rồi im ru. Bạn không có giấy tờ gì để kiện cáo. Agency tốt chia phí làm 3–4 đợt theo tiến trình hồ sơ (LC done, I-140 done...)." },
  { cat: "agency", q: "Tiêu chí lựa chọn agency tốt là gì?", a: '<b>Kỹ thuật:</b> Có giấy phép kinh doanh; luật sư di trú Mỹ đứng tên I-140/PERM; cung cấp tên công ty Mỹ, EIN, job description rõ ràng; hợp đồng song ngữ có điều khoản hoàn tiền.<br><b>Cảm quan:</b> Nói chuyện rõ ràng, không "nổ"; tiến độ thanh toán hợp lý (từng giai đoạn); hỗ trợ sát sao qua email. <em>Không agency nào hoàn hảo 100% — tìm cái tương đối phù hợp với mình là được.</em>' },
  { cat: "agency", q: "Dấu hiệu agency bất ổn là gì?", a: '⚠️ Hứa đậu 100% hoặc hứa làm xong trong 2.5–3 năm; không cho biết hãng bảo trợ; không có hợp đồng/hóa đơn; thu gần hết tiền từ đầu; chỉ liên lạc qua điện thoại/Zalo (không có email chính thức); có post bóc phốt từ cộng đồng; đặt cọc ít rồi "qua Mỹ đóng phần còn lại".' },
  { cat: "agency", q: "Có nên mở 2 hồ sơ cho 2 vợ chồng để tăng cơ hội không?", a: "Tùy hoàn cảnh. Nếu mở 2 cùng 1 agency — xác suất giống nhau, không thêm được gì. Nếu muốn mở 2, nên <em>chọn agency khác nhau, job khác nhau, mở lệch nhau vài tuần</em>. Nhưng đến bước DS-260, mỗi người chỉ được chọn 1 hồ sơ (không thể có 2 đơn xin định cư cùng lúc)." },
  { cat: "quy-trinh", q: "Bao lâu có case number? Case number là gì?", a: "<b>Case number</b> là mã số DOL cấp ngay khi nhận đơn LC của hãng. Bao lâu có case number phụ thuộc vào thời điểm hãng nộp đơn lên DOL. Nếu bạn mở hồ sơ gần ngày hãng nộp — có thể vài ngày. Nếu vừa qua đợt nộp — có thể 1–2 tháng. <em>Hỏi agency: bao giờ hãng có đợt nộp tiếp theo?</em>" },
  { cat: "quy-trinh", q: "LC được duyệt bao lâu? Nếu bị Audit thì sao?", a: "LC thường mất 12–18 tháng. Kết quả: <em>Certified</em> (duyệt — chuyển sang I-140 trong 180 ngày); <em>Audit</em> (cần bổ sung hồ sơ — thêm 6–9 tháng); <em>Denied/Withdrawn</em> (mất PD cũ, phải mở hồ sơ mới). Sau khi LC certified, bạn mới biết chắc hồ sơ đúng của mình qua form ETA-9089 có tên đương đơn." },
  { cat: "quy-trinh", q: "Có nên nộp I-140 gói Premium không?", a: "<b>VB chậm như hiện tại:</b> Gói premium chỉ hoàn thành sớm bước I-140, nhưng không rút ngắn tổng thời gian (vẫn chờ Visa Bulletin). Lợi ích: yên tâm hơn về sponsor, biết kết quả sớm. Bất lợi: tốn thêm $2,805; ảnh hưởng CSPA nếu có con gần 21t (time duyệt I-140 không được cộng vào để tính tuổi CSPA)." },
  { cat: "quy-trinh", q: "So sánh EB-3 Truyền Thống và Chuyển Diện?", a: "<b>Truyền thống:</b> Chờ ở VN; chi phí thấp hơn; thủ tục đơn giản hơn; làm việc ngay khi có thẻ xanh; thời gian 7–9 năm.<br><b>Chuyển diện:</b> Qua Mỹ sớm hơn; con học Mỹ sớm; phức tạp hơn (cần visa Mỹ, F1, I-485, EAD); chi phí cao hơn, phát sinh nhiều; phải chờ EAD mới làm việc hợp pháp (3–4 năm). <em>Chuyển diện chỉ nên làm khi tài chính rất mạnh, có người thân ở Mỹ hỗ trợ.</em>" },
  { cat: "quy-trinh", q: "Điều kiện để làm chuyển diện?", a: "Cần: có visa Mỹ B1/B2 (hoặc đang F1, H1B...); tài chính đủ sống 3–4 năm không thu nhập; có người thân ở Mỹ hỗ trợ việc làm; kế hoạch rõ ràng về tài chính và tâm lý. <em>Cảnh báo 2025:</em> ICE đang tăng cường kiểm tra, chính sách AOS có thể siết chặt — cân nhắc kỹ trước khi quyết định." },
  { cat: "quy-trinh", q: "Sau khi phỏng vấn không đậu, làm gì tiếp theo?", a: "Phụ thuộc vào kết quả: <em>221(g)</em> — bổ sung giấy tờ theo yêu cầu rồi chờ xét lại; <em>Từ chối vĩnh viễn</em> — cần mở hồ sơ mới hoặc nhờ luật sư kháng cáo; <em>Bị nghi hồ sơ gian dối</em> — cần cẩn thận, tỷ lệ rớt cao khi nộp lại. Chuẩn bị phỏng vấn kỹ 3 mảng: thông tin hồ sơ, công việc, quan hệ gia đình." },
  { cat: "quy-trinh", q: "Tại sao hãng bảo trợ chờ mình 5–7 năm?", a: "Hãng đã lên kế hoạch tuyển cuốn chiếu từng năm một — không phải chờ riêng bạn. Lý do hãng muốn lao động EB-3: ổn định hơn lao động trong nước (ít nghỉ đột xuất); chi phí lương thấp hơn; đương đơn có xu hướng làm việc tốt hơn (lo sợ vi phạm ảnh hưởng thẻ xanh). Hãng không mất tiền bảo trợ — tất cả phí đều do đương đơn trả." },
  { cat: "quy-trinh", q: "Tại sao hợp đồng chỉ yêu cầu làm 1 năm dù hãng chờ 5–7 năm?", a: 'Luật lao động Mỹ coi ràng buộc hợp đồng quá dài là "lao động cưỡng bức". 1 năm là đủ để chứng minh bạn có ý định lao động thật. Nếu nghỉ trước 6 tháng–1 năm, USCIS có thể nghi ngờ và gây khó khăn khi gia hạn thẻ xanh hoặc thi quốc tịch.' },
  { cat: "cspa", q: "CSPA là gì? Ảnh hưởng thế nào đến con cái?", a: "<b>CSPA (Child Status Protection Act)</b>: Bảo vệ tình trạng di trú của trẻ dưới 21t đi kèm khi hồ sơ chờ quá lâu. Công thức: <em>Tuổi CSPA = Tuổi thật ngày tới hạn − Thời gian chờ duyệt I-140</em>. Chỉ cần chú ý nếu con đang 14–15t khi mở hồ sơ. Sau CSPA 2025, dùng Final Action Dates (Bảng A) thay vì Dates for Filing để chốt tuổi — có thể bất lợi hơn cho con gần 21t." },
  { cat: "cspa", q: "Mình có con 15 tuổi, hồ sơ mất 7–8 năm, con có đi theo được không?", a: 'Phụ thuộc vào CSPA. Cần tính: tuổi thật của con ngày PD đáo hạn Bảng A trừ thời gian chờ I-140. Nếu kết quả < 21 tuổi và con chưa kết hôn, và bạn có "sought to acquire" (hành động xin visa cho con) trong 1 năm kể từ ngày tới hạn — con vẫn được đi theo. Cần trao đổi kỹ với luật sư di trú của agency để tính chính xác cho trường hợp cụ thể.' },
  { cat: "cspa", q: "Trước khi mở hồ sơ, có thể nhận cháu làm con nuôi để đưa đi theo không?", a: "Pháp luật không cấm nhận con nuôi. Nhưng USCIS rất nghiêm ngặt: việc nhận nuôi phải xảy ra trước khi bé đủ 16 tuổi, phải sống cùng và chăm sóc thực sự ít nhất 2 năm. <em>USCIS rất nghi ngờ trường hợp nhận con nuôi gần thời điểm mở hồ sơ.</em> Nếu bị phát hiện gian dối: toàn bộ hồ sơ có thể bị từ chối và bị cấm nộp tiếp." },
  { cat: "life", q: "Sau khi có thẻ xanh, mình 45 tuổi có làm được gì ở Mỹ không?", a: "Rất nhiều việc. Người Mỹ không phân biệt tuổi như ở Việt Nam — <em>hãng xưởng thích nhất lao động 40–60t vì chín chắn, có trách nhiệm</em>. Gợi ý: làm hãng xưởng/lắp ráp (20–60t); nail (học vài tháng, thu nhập tốt); phụ bếp/nhà hàng; chăm sóc người già; Uber/Doordash (21t+). Sau 1 năm làm cho hãng bảo trợ, bạn tự do chọn việc." },
  { cat: "life", q: "Mua xe ở Mỹ như thế nào? Bao nhiêu tiền?", a: "Xe cũ là lựa chọn phổ biến khi mới qua. <em>Không nên mua dưới $6,000–7,000</em> — xe quá cũ tiền sửa còn nhiều hơn tiền xe. Khoảng $10,000–15,000 cho xe cũ đáng tin cậy (Honda, Toyota 2014–2018). Mua tại CarMax, Carvana (có bảo hành, kiểm tra kỹ), hoặc qua cộng đồng người Việt. Cần: bằng lái, bảo hiểm, đăng ký DMV." },
  { cat: "life", q: "Chi phí thuê nhà và sinh hoạt ở Mỹ bao nhiêu?", a: "Phụ thuộc bang và thành phố. Texas (Houston, Dallas): nhà $800–1,500/tháng. California (LA, Orange County): $1,500–2,500. Georgia (Atlanta): $900–1,400. Chi phí sinh hoạt tháng đầu (không có người thân): $2,000–4,000 (điện, đồ đạc, đi lại, ăn uống). <em>Chuẩn bị ít nhất 3–4 tháng chi phí sinh hoạt trước khi sang.</em>" },
  { cat: "life", q: "F1/F2 có được đi làm không (cho chuyển diện)?", a: "F1 được làm on-campus tối đa 20h/tuần. Không được làm ngoài trường trừ khi có OPT/CPT. F2 (vợ/chồng của F1) <em>không được đi làm</em>. Chỉ sau khi nộp I-485 và được cấp EAD mới được đi làm hợp pháp full-time. Hiện EAD mất khoảng 3–6 tháng để được cấp." },
];
